### ISSUE TITLE
Honor Jest default config

### ISSUE THREAD

**Issue by acostalima** [moxystudio/jest-config#9]
Consider the following snippet:

```js
'use strict';

const { compose, baseConfig } = require('@moxy/jest-config');
const { defaults } = require('jest-config');

module.exports = compose([
    baseConfig,
    (config) => ({
        ...config,
        setupFiles: ['<rootDir>/jest.setup'],
        coveragePathIgnorePatterns: [
            ...defaults.coveragePathIgnorePatterns,
            '<rootDir>/test/utils/',
        ],
    }),
]);
```

I'd expect `config` to already provide sensible defaults instead of having to install `jest-config` myself to retrieve the [default configurations](https://jestjs.io/docs/en/configuration#defaults).

**Comment by threequartersjohn** [comment]
Hmm, do you think this could be added as an addon, similar to `[withWeb](https://github.com/moxystudio/jest-config/tree/master/lib/addons/with-web)` or `[withRTL](https://github.com/moxystudio/jest-config/tree/master/lib/addons/with-rtl)`?

I'm unclear whether it would be ideal to have out configuration rest on top of other default configurations, because it tips the workload significantly towards developers who would like to use this package but avoid Jest's default configuration. Ideally, it would be balanced out. Also, i appreciate that our config is built on a _tabula rasa_, and this would pollute it considerably. 

That said, i feel like adding this as an addon would be an ideal solution that would make it easier for both developers who want it, and remain the same for those who don't. It would also avoid breaking the existing contract. What do you think?

**Comment by acostalima** [comment]
I'm not sure whether developing a new addon is the right direction. The defaults could provided by `baseConfig` in my opinion.
Just to give some context, when I was putting together my Jest config, the first thing that crossed my mind about `config.coveragePathIgnorePatterns` was that it already provided some common paths to ignore, namely `node_modules` which is Jest's default. In my use case above, I had to override `coveragePathIgnorePatterns` but still wanted to ignore `node_modules` nonetheless. I realized out Jest config does not configure `coveragePathIgnorePatterns`, so it threw an error indicating it could not be spreaded as it is not an iterable.
We don't need really to use Jest's default configuration per se, but at least I think we should still provide some good defaults for some settings, being `coveragePathIgnorePatterns` one of them.

**Comment by acostalima** [comment]
@moxystudio/developers thoughts?

**Comment by satazor** [comment]
@acostalima as you noticed, currently, the baseConfig contains only a few overrides and not the whole config. This means you have to deal with possible things being empty and you have to deal with it accordingly, e.g.: https://github.com/moxystudio/jest-config/blob/master/lib/addons/with-rtl/index.js#L5.

We could have our baseConfig on top of `jest-config`, the only downside I see is that it becomes "polluted" but I'm fine with it. I would say it's a welcome change.
